export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MEASUREMENT_OUT_OF_RANGE: "MEASUREMENT_OUT_OF_RANGE",
  RATED_TEMP_OUT_OF_RANGE: "RATED_TEMP_OUT_OF_RANGE",
  COLOR_TEMP_SETTING_INVALID: "COLOR_TEMP_SETTING_INVALID",
  CUE_ALREADY_PUBLISHED: "CUE_ALREADY_PUBLISHED",
  CUE_PUBLISH_BLOCKED: "CUE_PUBLISH_BLOCKED"
} as const;
