export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CCT_READING_INVALID: "CCT_READING_INVALID",
  CCT_RATED_INVALID: "CCT_RATED_INVALID",
  CCT_PUBLISH_BLOCKED: "CCT_PUBLISH_BLOCKED"
} as const;
